import Inbox from "@/components/Inbox";
import { Chat } from "@/types";

export default function ChatPage() {
  return <Inbox inboxes={mockChats} />;
}

// Example: 20 mock Chat objects
export const mockChats: Chat[] = [
  {
    id: "1",
    body: "Hello! How can I help you today?",
    sender: "bot",
    avatar: "/avatars/bot1.png",
    createdAt: "2025-08-11T09:00:00Z",
    name: "Gemini Bot",
  },
  {
    id: "2",
    body: "What's the weather like in Paris?",
    sender: "user",
    avatar: "/avatars/user1.png",
    createdAt: "2025-08-11T09:01:00Z",
    name: "Alice",
  },
  {
    id: "3",
    body: "It's sunny and 25°C in Paris.",
    sender: "bot",
    avatar: "/avatars/bot1.png",
    createdAt: "2025-08-11T09:01:05Z",
    name: "Gemini Bot",
  },
  {
    id: "4",
    body: "Can you summarize this article for me?",
    sender: "user",
    avatar: "/avatars/user2.png",
    createdAt: "2025-08-11T09:02:00Z",
    name: "Bob",
  },
  {
    id: "5",
    body: "Sure! Please provide the article link.",
    sender: "bot",
    avatar: "/avatars/bot1.png",
    createdAt: "2025-08-11T09:02:10Z",
    name: "Gemini Bot",
  },
  {
    id: "6",
    body: "Here is the link: https://example.com/article",
    sender: "user",
    avatar: "/avatars/user2.png",
    createdAt: "2025-08-11T09:02:20Z",
    name: "Bob",
  },
  {
    id: "7",
    body: "The article discusses the benefits of AI in healthcare...",
    sender: "bot",
    avatar: "/avatars/bot1.png",
    createdAt: "2025-08-11T09:02:30Z",
    name: "Gemini Bot",
  },
  {
    id: "8",
    body: "Thank you!",
    sender: "user",
    avatar: "/avatars/user2.png",
    createdAt: "2025-08-11T09:02:40Z",
    name: "Bob",
  },
  {
    id: "9",
    body: "You're welcome! Anything else I can help with?",
    sender: "bot",
    avatar: "/avatars/bot1.png",
    createdAt: "2025-08-11T09:02:45Z",
    name: "Gemini Bot",
  },
  {
    id: "10",
    body: "Tell me a joke.",
    sender: "user",
    avatar: "/avatars/user3.png",
    createdAt: "2025-08-11T09:03:00Z",
    name: "Charlie",
  },
  {
    id: "11",
    body: "Why did the computer show up at work late? It had a hard drive!",
    sender: "bot",
    avatar: "/avatars/bot1.png",
    createdAt: "2025-08-11T09:03:10Z",
    name: "Gemini Bot",
  },
  {
    id: "12",
    body: "Haha, that's funny!",
    sender: "user",
    avatar: "/avatars/user3.png",
    createdAt: "2025-08-11T09:03:15Z",
    name: "Charlie",
  },
  {
    id: "13",
    body: "Can you translate 'hello' to Spanish?",
    sender: "user",
    avatar: "/avatars/user4.png",
    createdAt: "2025-08-11T09:04:00Z",
    name: "Dana",
  },
  {
    id: "14",
    body: "'Hello' in Spanish is 'Hola'.",
    sender: "bot",
    avatar: "/avatars/bot1.png",
    createdAt: "2025-08-11T09:04:05Z",
    name: "Gemini Bot",
  },
  {
    id: "15",
    body: "What's the capital of Japan?",
    sender: "user",
    avatar: "/avatars/user5.png",
    createdAt: "2025-08-11T09:05:00Z",
    name: "Eve",
  },
  {
    id: "16",
    body: "The capital of Japan is Tokyo.",
    sender: "bot",
    avatar: "/avatars/bot1.png",
    createdAt: "2025-08-11T09:05:05Z",
    name: "Gemini Bot",
  },
  {
    id: "17",
    body: "Remind me to call John at 3 PM.",
    sender: "user",
    avatar: "/avatars/user1.png",
    createdAt: "2025-08-11T09:06:00Z",
    name: "Alice",
  },
  {
    id: "18",
    body: "Reminder set to call John at 3 PM.",
    sender: "bot",
    avatar: "/avatars/bot1.png",
    createdAt: "2025-08-11T09:06:05Z",
    name: "Gemini Bot",
  },
  {
    id: "19",
    body: "What's 15 multiplied by 7?",
    sender: "user",
    avatar: "/avatars/user2.png",
    createdAt: "2025-08-11T09:07:00Z",
    name: "Bob",
  },
  {
    id: "20",
    body: "15 multiplied by 7 is 105.",
    sender: "bot",
    avatar: "/avatars/bot1.png",
    createdAt: "2025-08-11T09:07:05Z",
    name: "Gemini Bot",
  },
];
