name: capital-h-app

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: capital_h_dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      BUN_HOT: 1
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - .env.development:/app/.env
    tmpfs:
      - /app/.next
    profiles:
      - dev

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capital_h_prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - .env.production:/app/.env
    profiles:
      - prod

volumes:
  node_modules:
