# Development
FROM node:20-alpine AS dev
WORKDIR /app
COPY package.json bun.lock ./
RUN npm install -g bun && bun install
COPY . .
EXPOSE 3000
CMD ["bun", "dev"]

# Production
FROM node:20-alpine AS prod
WORKDIR /app
COPY package.json bun.lock ./
RUN npm install -g bun && bun install --production
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["bun", "start"]
